# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tuning.proto
# flake8: noqa
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import hlo_pb2 as hlo__pb2
from . import xla_data_pb2 as xla__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ctuning.proto\x12\ntpu_graphs\x1a\thlo.proto\x1a\x0exla_data.proto";\n\nTuningData\x12-\n\x07modules\x18\x01 \x03(\x0b\x32\x1c.tpu_graphs.ModuleTuningData"\x93\x01\n\x10ModuleTuningData\x12#\n\x06module\x18\x01 \x01(\x0b\x32\x13.xla.HloModuleProto\x12\x13\n\x0b\x66ingerprint\x18\x02 \x01(\x04\x12\'\n\x04runs\x18\x03 \x03(\x0b\x32\x19.tpu_graphs.ConfigProfile\x12\x1c\n\x14\x63onfig_index_to_node\x18\x04 \x03(\x04"\xc8\x01\n\rConfigProfile\x12,\n\top_config\x18\x01 \x01(\x0b\x32\x17.tpu_graphs.HloOpConfigH\x00\x12\x34\n\rmodule_config\x18\x02 \x01(\x0b\x32\x1b.tpu_graphs.HloModuleConfigH\x00\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\x12&\n\x07profile\x18\x04 \x01(\x0b\x32\x15.xla.ExecutionProfile\x12\x12\n\nis_default\x18\x05 \x01(\x08\x42\x08\n\x06\x63onfig"C\n\x0bHloOpConfig\x12\x34\n\x10tile_size_config\x18\x01 \x01(\x0b\x32\x1a.tpu_graphs.TileSizeConfig"n\n\x0eTileSizeConfig\x12\x15\n\rkernel_bounds\x18\x01 \x03(\x03\x12\x15\n\routput_bounds\x18\x02 \x03(\x03\x12\x14\n\x0cinput_bounds\x18\x03 \x03(\x03\x12\x18\n\x10iteration_bounds\x18\x04 \x03(\x03"B\n\x0fHloModuleConfig\x12/\n\rlayout_config\x18\x01 \x01(\x0b\x32\x18.tpu_graphs.LayoutConfig"\xd0\x01\n\x0cLayoutConfig\x12\x38\n\x05nodes\x18\x01 \x03(\x0b\x32).tpu_graphs.LayoutConfig.NodeLayoutConfig\x1a\x85\x01\n\x10NodeLayoutConfig\x12M\n\x07tensors\x18\x01 \x03(\x0b\x32<.tpu_graphs.LayoutConfig.NodeLayoutConfig.TensorLayoutConfig\x1a"\n\x12TensorLayoutConfig\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tuning_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_TUNINGDATA"]._serialized_start = 55
    _globals["_TUNINGDATA"]._serialized_end = 114
    _globals["_MODULETUNINGDATA"]._serialized_start = 117
    _globals["_MODULETUNINGDATA"]._serialized_end = 264
    _globals["_CONFIGPROFILE"]._serialized_start = 267
    _globals["_CONFIGPROFILE"]._serialized_end = 467
    _globals["_HLOOPCONFIG"]._serialized_start = 469
    _globals["_HLOOPCONFIG"]._serialized_end = 536
    _globals["_TILESIZECONFIG"]._serialized_start = 538
    _globals["_TILESIZECONFIG"]._serialized_end = 648
    _globals["_HLOMODULECONFIG"]._serialized_start = 650
    _globals["_HLOMODULECONFIG"]._serialized_end = 716
    _globals["_LAYOUTCONFIG"]._serialized_start = 719
    _globals["_LAYOUTCONFIG"]._serialized_end = 927
    _globals["_LAYOUTCONFIG_NODELAYOUTCONFIG"]._serialized_start = 794
    _globals["_LAYOUTCONFIG_NODELAYOUTCONFIG"]._serialized_end = 927
    _globals["_LAYOUTCONFIG_NODELAYOUTCONFIG_TENSORLAYOUTCONFIG"]._serialized_start = 893
    _globals["_LAYOUTCONFIG_NODELAYOUTCONFIG_TENSORLAYOUTCONFIG"]._serialized_end = 927
# @@protoc_insertion_point(module_scope)
